name: Master build

on:
  push:
    branches: [ "master" ]

jobs:
  clean:
    uses: tracefy/github-actions-workflows/.github/workflows/utilities-clean.yml@v1
  todo:
    needs:
      - clean
    uses: tracefy/github-actions-workflows/.github/workflows/utilities-todo.yml@v1
  tag:
    needs:
      - clean
    uses: ./.github/workflows/docker-tag.yml
    secrets: inherit
    with:
      tag: latest
  deploy:
    needs:
      - tag
    uses: tracefy/github-actions-workflows/.github/workflows/docker-deploy.yml@v1
    secrets:
      host: ${{ secrets.SSH_HOST_TCFADCK001 }}
      registry: ${{ secrets.REGISTRY }} 
      GH_PA_TOKEN: ${{ secrets.GH_PA_TOKEN }}
      GH_PA_USER: ${{ secrets.GH_PA_USER }}
    with:
      tag: latest
